#!/usr/bin/python3
print('Content-type:text/html\n\n')
print('<html>')
print('<head>')
print('<title>Authentication of a Sailor</title>')
print('</head>')
print('<body>')
print('<h3>Authenticate Sailor')

print('<form action="authenticate_sailor.cgi" method="post">')
print('<p>Start Date: <input type="text" name="start_date"/></p>')
print('<p>End Date: <input type="text" name="end_date"/></p>')
print('<p>Country: <input type="text" name="country"/></p>')
print('<p>CNI: <input type="text" name="cni"/></p>')
print('<p>Authenticator Email: <input type="text" name="email"/></p>')
print('<p><input type="submit" value="Submit"/></p>')
print('</form>')

print('</body>')
print('</html>')